Backlog
leif81/bzkanban pull request #51
Opened 2017-01-08 03:38 UTC by gizzmojr

Ability to show the default 'null' (---) milestone of a product, even when a different milestone is loaded. 
This is also filtering for unconfirmed/confirmed bugs.
Displayed as an extra column on the left, for quick reorganizing of cards.

The search query at the global vars allows this to be modified as needed.

2017-01-08 20:46 UTC, leif81 requested changes
Nice work. 

I pushed a few commits with changes to the branch. Take a look at those. Some of which were easier to fix then try to suggest in the review.

For others I added some inline comments with a few small suggestions to fix. 

Also, I haven't tried it yet, but I presume when we drag a card from the backlog column into say CONFIRMED that it updates the milestone for the bug? I didn't see new logic added for that, but maybe it just-works with existing drag and drop?

2017-01-08 20:46 UTC, leif81 commented on bzkanban.js
> +var backlogSearch = "&target_milestone=---&bug_status=UNCONFIRMED&bug_status=CONFIRMED";
Lets prefix these global vars with "bz" like the others.

2017-01-08 20:46 UTC, leif81 commented on bzkanban.js
>          nav.appendChild(createBacklogTarget());
Maybe we can get rid of the old backlog target now? I think intuitively now backlogging a card would be done by dragging it into the backlog column.

2017-01-08 20:46 UTC, leif81 commented on bzkanban.js
> +        var button = document.getElementById("btnShow" + backlogTitle);
Lets reuse the `backlogShowButton` var from above instead of looking it up.

2017-01-08 20:52 UTC, leif81 commented on bzkanban.js
>          nav.appendChild(createBacklogTarget());
I'm also thinking it'd be better if we put the show backlog button in the `actions` span on the right hand side.

2017-01-08 20:58 UTC, leif81 commented
Btw, while this feature branch does exactly what we were brainstorming the other day...I'm feeling slightly reserved about declaring judgement as to if it'll be as useful as we hoped. WDYT?

2017-01-08 21:00 UTC, leif81 commented on bzkanban.js
> +        var button = document.getElementById("btnShow" + backlogTitle);
Also, noticed that the state of the button will need to get reset when switching products.

2017-01-08 21:02 UTC, leif81 commented on bzkanban.js
> +            backlogCol.style.display = "none";
We should refactor this into a `showBacklog()` and `hideBacklog()` functions.

2017-01-08 21:02 UTC, leif81 commented on bzkanban.js
> +        backlog.style.display = 'none';
We could use the `hideBacklog()` function call here.

2017-01-08 21:03 UTC, leif81 commented on bzkanban.js
> +            backlogCol.style.display = "none";
And on switching products we could just call `hideBacklog()`.

2017-01-09 20:10 UTC, leif81 commented on bzkanban.js
> +var backlogSearch = "&target_milestone=---&bug_status=UNCONFIRMED&bug_status=CONFIRMED";
Can we use empty resolution instead of bug_status field?

2017-01-11 15:33 UTC, gizzmojr commented
Still need to move the button into the nav

2017-01-11 16:07 UTC, gizzmojr commented
Ok this feels like a good point to consider merging it in. Good feel for it, I'm really digging the functionality versus the old drop-target we had.

2017-01-12 02:51 UTC, leif81 commented on bzkanban.js
> +    httpGet("/rest.cgi/bug?product=" + bzProduct + bzBacklogSearch, function(response) {
Lets also add the same `include_fields=` param to this query that we use in our `loadBugs` function. That should trim down the response size a lot.

2017-01-12 02:52 UTC, gizzmojr commented on bzkanban.js
> +            loadBacklogCards();
In 868dd250d489f5f4b5cea943e18a7c494ae91948, this has been bypassed. Was going to remove unless you want to refactor.

2017-01-12 02:54 UTC, leif81 commented on bzkanban.js
> +    httpGet("/rest.cgi/bug?product=" + bzProduct + bzBacklogSearch, function(response) {
Hmm actually...it'd be really nice if we could re-use the `bzRestGetBugsUrl ` value here and just tack on `resolution=---`. The only problem with that is the `target_milestone` wouldn't be right. So close.

2017-01-12 02:59 UTC, leif81 commented on bzkanban.js
> +            loadBacklogCards();
Ya not sure we should load the backlog cards in `loadBoard`. Some backlogs are pretty massive. And unless the user opens the backlog, which is probably a somewhat rare action, it'll be an unnecessary extra load happening.

2017-01-12 03:04 UTC, leif81 commented on bzkanban.js
> +    loadBacklogCards();
Doing this here is probably too soon. If it's needed to refresh page after drag and drop, could wrap it in a check that the backlog is shown.

2017-01-12 03:04 UTC, gizzmojr commented on bzkanban.js
> +    httpGet("/rest.cgi/bug?product=" + bzProduct + bzBacklogSearch, function(response) {
Good call making the filtered URL.

2017-01-12 03:08 UTC, leif81 commented on bzkanban.js
> +    if (backlogCol.style.display === "none" || null) {
What's the `|| null` part for?

2017-01-12 03:12 UTC, gizzmojr commented on bzkanban.js
> +    if (backlogCol.style.display === "none" || null) {
There was a point where we were checking the state of the column but it hadn't been explicitly set to none but was expecting a state that it isn't visible.

2017-01-12 03:38 UTC, leif81 commented on bzkanban.js
> +    if (backlogCol.style.display === "none" || null) {
K, the `|| null` is probably not what you want then. I think you want `if (backlogCol.style.display === "none" || backlogCol.style.display === null)`

2017-01-12 03:40 UTC, leif81 commented on bzkanban.js
> +    if (backlogCol.style.display === "none" || null) {
And since it's looking like we're going to use that check in two or three places now we should turn that into a function like `isBacklogVisible()`.

2017-01-12 04:04 UTC, gizzmojr commented on bzkanban.js
> +    if (backlogCol.style.display === "none" || null) {
:+1: to all that, done.
Removed the null check all together. Seems to be working fine for me.

2017-01-15 23:38 UTC, leif81 approved these changes

2017-01-15 23:38 UTC, merged

2017-01-15 23:39 UTC, leif81 commented
Looks really good! 👍